"""fusion classe et personnes concernees

Revision ID: 1c53cdbfe9ed
Revises: 423ae57f5a83
Create Date: 2026-09-15 20:04:08.357913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c53cdbfe9ed'
down_revision = '423ae57f5a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe_personnes_concernees', sa.String(length=255), nullable=True))
        batch_op.drop_column('personnes_concernees')
        batch_op.drop_column('classe_concernee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe_concernee', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('personnes_concernees', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('classe_personnes_concernees')

    # ### end Alembic commands ###
