"""Ajoute les services recommandes aux tickets

Revision ID: 3ff2098b6a9d
Revises: 43f15c3fd56b
Create Date: 2026-09-17 14:17:05.526879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff2098b6a9d'
down_revision = '43f15c3fd56b'
branch_labels = None
depends_on = None


def upgrade():
    # Ajout temporaire de la colonne avec une valeur par défaut côté PostgreSQL.
    # Cela permet aux tickets déjà existants de recevoir une liste vide.
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'recommended_services',
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'::json")
            )
        )

    # Le défaut SQL n'est nécessaire que pour effectuer la migration.
    # Les nouveaux tickets seront ensuite initialisés par l'application.
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column(
            'recommended_services',
            server_default=None
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('recommended_services')

    # ### end Alembic commands ###
