"""integration modeles J2

Revision ID: 423ae57f5a83
Revises: eaabe1c5de5d
Create Date: 2026-09-15 19:52:36.353849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423ae57f5a83'
down_revision = 'eaabe1c5de5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('request_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('classe_concernee', sa.String(length=100), nullable=True),
    sa.Column('personnes_concernees', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('students_pseudo_key'), type_='unique')
        batch_op.drop_column('pseudo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pseudo', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('students_pseudo_key'), ['pseudo'], postgresql_nulls_not_distinct=False)

    op.drop_table('ticket_tags')
    op.drop_table('tickets')
    op.drop_table('tags')
    op.drop_table('request_types')
    # ### end Alembic commands ###
