"""Ajoute le scope des personnes concernees aux tickets

Revision ID: 81ef4cbdedc2
Revises: e2de5a974f1a
Create Date: 2026-09-17 12:08:52.409223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ef4cbdedc2'
down_revision = 'e2de5a974f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('scope')

    # ### end Alembic commands ###
