"""ajoute verification email etudiant

Revision ID: e2de5a974f1a
Revises: 1c53cdbfe9ed
Create Date: 2026-09-15 23:50:56.505781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2de5a974f1a'
down_revision = '1c53cdbfe9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('confirmation_code')

    # ### end Alembic commands ###
